/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';


import {
  MyName as SubmissionStatusButton
} from './components/submission-status-button/submission-status-button';

declare global {
  interface HTMLSubmissionStatusButtonElement extends SubmissionStatusButton, HTMLElement {
  }
  var HTMLSubmissionStatusButtonElement: {
    prototype: HTMLSubmissionStatusButtonElement;
    new (): HTMLSubmissionStatusButtonElement;
  };
  interface HTMLElementTagNameMap {
    "submission-status-button": HTMLSubmissionStatusButtonElement;
  }
  interface ElementTagNameMap {
    "submission-status-button": HTMLSubmissionStatusButtonElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "submission-status-button": JSXElements.SubmissionStatusButtonAttributes;
    }
  }
  namespace JSXElements {
    export interface SubmissionStatusButtonAttributes extends HTMLAttributes {
      
    }
  }
}

